// This is a server-side file.
'use server';

/**
 * @fileOverview Generates a reasoned error message using AI for unexpected values.
 *
 * - generateReasonedErrorMessage - A function that takes an unexpected value and returns a helpful error message.
 * - ReasonedErrorMessageInput - The input type for the generateReasonedErrorMessage function.
 * - ReasonedErrorMessageOutput - The return type for the generateReasonedErrorMessage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ReasonedErrorMessageInputSchema = z.object({
  unexpectedValue: z.any().describe('The unexpected value that caused the error.'),
  context: z.string().describe('The context in which the unexpected value occurred.'),
});
export type ReasonedErrorMessageInput = z.infer<typeof ReasonedErrorMessageInputSchema>;

const ReasonedErrorMessageOutputSchema = z.object({
  errorMessage: z.string().describe('A helpful error message generated by AI.'),
});
export type ReasonedErrorMessageOutput = z.infer<typeof ReasonedErrorMessageOutputSchema>;

export async function generateReasonedErrorMessage(input: ReasonedErrorMessageInput): Promise<ReasonedErrorMessageOutput> {
  return reasonedErrorMessageFlow(input);
}

const prompt = ai.definePrompt({
  name: 'reasonedErrorMessagePrompt',
  input: {schema: ReasonedErrorMessageInputSchema},
  output: {schema: ReasonedErrorMessageOutputSchema},
  prompt: `You are an AI assistant designed to generate helpful error messages.

  An unexpected value was encountered in the following context: {{{context}}}

  The unexpected value is: {{{unexpectedValue}}}

  Generate a concise and user-friendly error message that explains why the value is unexpected and how the user can fix the issue.
`,
});

const reasonedErrorMessageFlow = ai.defineFlow(
  {
    name: 'reasonedErrorMessageFlow',
    inputSchema: ReasonedErrorMessageInputSchema,
    outputSchema: ReasonedErrorMessageOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
